export const LOG_IN = 'LOG_IN';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAIL = 'LOG_IN_FAIL';

export const GET_USER_SESSION_STORAGE = 'GET_USER_SESSION_STORAGE';

export const GET_ROLES = 'GET_ROLES';
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const GET_ROLES_FAILS = 'GET_ROLES_FAILS';

export const GET_MEMBERS_OF_COMPANY = 'GET_MEMBERS_OF_COMPANY';
export const GET_MEMBERS_OF_COMPANY_SUCCESS = 'GET_MEMBERS_OF_COMPANY_SUCCESS';
export const GET_MEMBERS_OF_COMPANY_FAILS = 'GET_MEMBERS_OF_COMPANY_FAILS';

export const LOG_OUT = 'LOG_OUT';